// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRnPptk3JFc9pEqSLE4Xgh_NHehS6Juu4',
    appId: '1:115119258346:web:d76ee70530b79e69c2f593',
    messagingSenderId: '115119258346',
    projectId: 'halftime-push-service',
    authDomain: 'halftime-push-service.firebaseapp.com',
    databaseURL: 'https://halftime-push-service.firebaseio.com',
    storageBucket: 'halftime-push-service.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkE5DiuMULkC-LZoCJm9_9TPaChGBI3x0',
    appId: '1:115119258346:android:2fc0190f79bd7195c2f593',
    messagingSenderId: '115119258346',
    projectId: 'halftime-push-service',
    databaseURL: 'https://halftime-push-service.firebaseio.com',
    storageBucket: 'halftime-push-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HuAywVBhAMLc2fUwIHv2hxF6nQKPjmQ',
    appId: '1:115119258346:ios:a3f29e92c51d3272c2f593',
    messagingSenderId: '115119258346',
    projectId: 'halftime-push-service',
    databaseURL: 'https://halftime-push-service.firebaseio.com',
    storageBucket: 'halftime-push-service.appspot.com',
    iosClientId: '115119258346-3llkup19sfk6lq622vht259e052dk76q.apps.googleusercontent.com',
    iosBundleId: 'com.dalrise.laudyou.laudyouApp',
  );
}
